# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Axonhub < Formula
  desc "All-in-one AI development platform. Use any SDK, access any model."
  homepage "https://github.com/looplj/axonhub"
  version "0.9.42"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/looplj/axonhub/releases/download/v0.9.42/axonhub_0.9.42_darwin_amd64.zip"
      sha256 "7e61a493b17ddb709521947c25ab69b50fdf6e71a41f53439af627ba519e60b5"

      define_method(:install) do
        libexec.install "axonhub"
        (etc/"axonhub").mkpath
        (bin/"axonhub").write <<~SH
          #!/bin/sh
          cd "#{etc}/axonhub" || exit 1
          exec "#{libexec}/axonhub" "$@"
        SH
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/looplj/axonhub/releases/download/v0.9.42/axonhub_0.9.42_darwin_arm64.zip"
      sha256 "d05be3f0e492bf94f599b86a337cda34cdfdf4fa0390d45796fadf7cc3b732fa"

      define_method(:install) do
        libexec.install "axonhub"
        (etc/"axonhub").mkpath
        (bin/"axonhub").write <<~SH
          #!/bin/sh
          cd "#{etc}/axonhub" || exit 1
          exec "#{libexec}/axonhub" "$@"
        SH
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/looplj/axonhub/releases/download/v0.9.42/axonhub_0.9.42_linux_amd64.zip"
      sha256 "901f9ada7f3d390acb32d80bbe7e78fec25174d093d9fd53c406a16e5a973a90"
      define_method(:install) do
        libexec.install "axonhub"
        (etc/"axonhub").mkpath
        (bin/"axonhub").write <<~SH
          #!/bin/sh
          cd "#{etc}/axonhub" || exit 1
          exec "#{libexec}/axonhub" "$@"
        SH
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/looplj/axonhub/releases/download/v0.9.42/axonhub_0.9.42_linux_arm64.zip"
      sha256 "a2535d009a708fb1dc00cb5ea821ee18d37c6959728e2b6a76f8167e677003ad"
      define_method(:install) do
        libexec.install "axonhub"
        (etc/"axonhub").mkpath
        (bin/"axonhub").write <<~SH
          #!/bin/sh
          cd "#{etc}/axonhub" || exit 1
          exec "#{libexec}/axonhub" "$@"
        SH
      end
    end
  end

  def caveats
    <<~EOS
      AxonHub runs with default configuration.
      To customize, create a config file at: #{etc}/axonhub/config.yml

      View current configuration:
        axonhub config preview

      The wrapper starts AxonHub from #{etc}/axonhub automatically.
    EOS
  end

  service do
    run [opt_bin/"axonhub"]
    keep_alive true
  end

  test do
    system "#{bin}/axonhub", "version"
  end
end
