# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Axonhub < Formula
  desc "All-in-one AI development platform. Use any SDK, access any model."
  homepage "https://github.com/looplj/axonhub"
  version "0.9.23"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/looplj/axonhub/releases/download/v0.9.23/axonhub_0.9.23_darwin_amd64.zip"
      sha256 "031d7228904e45c5ceddb594154b858122d7dd2b26c7d7f9eb22623621309d7a"

      define_method(:install) do
        libexec.install "axonhub"
        (etc/"axonhub").mkpath
        (bin/"axonhub").write <<~SH
          #!/bin/sh
          cd "#{etc}/axonhub" || exit 1
          exec "#{libexec}/axonhub" "$@"
        SH
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/looplj/axonhub/releases/download/v0.9.23/axonhub_0.9.23_darwin_arm64.zip"
      sha256 "647876e6be7596d5147f923660a624b710110c2cce27c91d36201d443752eaff"

      define_method(:install) do
        libexec.install "axonhub"
        (etc/"axonhub").mkpath
        (bin/"axonhub").write <<~SH
          #!/bin/sh
          cd "#{etc}/axonhub" || exit 1
          exec "#{libexec}/axonhub" "$@"
        SH
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/looplj/axonhub/releases/download/v0.9.23/axonhub_0.9.23_linux_amd64.zip"
      sha256 "baaa03d9075238c35b44602bcbc4480b3bd83b460123fb03a8a0f212fcce91e7"
      define_method(:install) do
        libexec.install "axonhub"
        (etc/"axonhub").mkpath
        (bin/"axonhub").write <<~SH
          #!/bin/sh
          cd "#{etc}/axonhub" || exit 1
          exec "#{libexec}/axonhub" "$@"
        SH
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/looplj/axonhub/releases/download/v0.9.23/axonhub_0.9.23_linux_arm64.zip"
      sha256 "d9c51c855dd71161eb6ed77bb272b41dea75bcd03c470304df9b123de9f2baf1"
      define_method(:install) do
        libexec.install "axonhub"
        (etc/"axonhub").mkpath
        (bin/"axonhub").write <<~SH
          #!/bin/sh
          cd "#{etc}/axonhub" || exit 1
          exec "#{libexec}/axonhub" "$@"
        SH
      end
    end
  end

  def caveats
    <<~EOS
      AxonHub runs with default configuration.
      To customize, create a config file at: #{etc}/axonhub/config.yml

      View current configuration:
        axonhub config preview

      The wrapper starts AxonHub from #{etc}/axonhub automatically.
    EOS
  end

  service do
    run [opt_bin/"axonhub"]
    keep_alive true
  end

  test do
    system "#{bin}/axonhub", "version"
  end
end
